src/Entity/Marcacoes.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MarcacoesRepository")
 */
class Marcacoes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $idCliente;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $servico1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $servico2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $servico3;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $servico4;

    /**
     * @ORM\Column(type="date")
     */
    private $marcacaoDia;

    /**
     * @ORM\Column(type="time")
     */
    private $marcacaoHora;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2, nullable=true)
     */
    private $valor;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $estado;

    /**
     * @ORM\Column(type="datetime")
     */
    private $registo;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $registo_update;

    public function __construct(){

        $this->registo = new \DateTime("now");
        $this->registo_update = new \DateTime("now");

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdCliente(): ?int
    {
        return $this->idCliente;
    }

    public function setIdCliente(int $idCliente): self
    {
        $this->idCliente = $idCliente;

        return $this;
    }

    public function getServico1(): ?string
    {
        return $this->servico1;
    }

    public function setServico1(string $servico1): self
    {
        $this->servico1 = $servico1;

        return $this;
    }

    public function getServico2(): ?string
    {
        return $this->servico2;
    }

    public function setServico2(?string $servico2): self
    {
        $this->servico2 = $servico2;

        return $this;
    }

    public function getServico3(): ?string
    {
        return $this->servico3;
    }

    public function setServico3(?string $servico3): self
    {
        $this->servico3 = $servico3;

        return $this;
    }

    public function getServico4(): ?string
    {
        return $this->servico4;
    }

    public function setServico4(?string $servico4): self
    {
        $this->servico4 = $servico4;

        return $this;
    }

    public function getMarcacaoDia(): ?\DateTimeInterface
    {
        return $this->marcacaoDia;
    }

    public function setMarcacaoDia(\DateTimeInterface $marcacaoDia): self
    {
        $this->marcacaoDia = $marcacaoDia;

        return $this;
    }

    public function getMarcacaoHora(): ?\DateTimeInterface
    {
        return $this->marcacaoHora;
    }

    public function setMarcacaoHora(\DateTimeInterface $marcacaoHora): self
    {
        $this->marcacaoHora = $marcacaoHora;

        return $this;
    }

    public function getValor(): ?string
    {
        return $this->valor;
    }

    public function setValor(?string $valor): self
    {
        $this->valor = $valor;

        return $this;
    }

    public function getEstado(): ?string
    {
        return $this->estado;
    }

    public function setEstado(string $estado): self
    {
        $this->estado = $estado;

        return $this;
    }

    public function getRegisto(): ?\DateTimeInterface
    {
        return $this->registo;
    }

    public function setRegisto(\DateTimeInterface $registo): self
    {
        $this->registo = $registo;

        return $this;
    }

    public function getRegistoUpdate(): ?\DateTimeInterface
    {
        return $this->registo_update;
    }

    public function setRegistoUpdate(?\DateTimeInterface $registo_update): self
    {
        $this->registo_update = $registo_update;

        return $this;
    }
}

src/Form/MarcacoesType.php
<?php

namespace App\Form;

use App\Entity\Marcacoes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;

class MarcacoesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('idCliente')
            ->add('servico1', ChoiceType::class, [
                'choices'=>[
                    'Escolha' => null,
                    'Manicure' => 'Manicure',
                    'Verniz gel' => 'Verniz gel',
                    'Manutenção de unhas de gel' => 'Manutenção de unhas de gel',
                    'Aplicação de unhas de gel sem entenção' => 'Aplicação de unhas de gel sem entenção',
                    'Aplicação de unhas de gel com entenção' => 'Aplicação de unhas de gel com entenção',
                    'Pedicure' => 'Pedicure',
                    'Pedicure verniz gel' => 'Pedicure verniz gel',
                    'Parafina' => 'Parafina',
                    '1--' => '',
                    'Depilação perna inteira' => 'Depilação perna inteira',
                    'Depilação meia perna' => 'Depilação meia perna',
                    'Depilação virilhas' => 'Depilação virilhas',
                    'Depilação axilas' => 'Depilação axilas',
                    'Depilação buco' => 'Depilação buco',
                    'Depilação sobrancelhas' => 'Depilação sobrancelhas',
                    'Depilação pack' => 'Depilação pack',
                    'Depilação masculina ao peito' => 'Depilação masculina ao peito',
                    '2--' => '',
                    'Limpeza facial hidratação' => 'Limpeza facial hidratação',
                    'Limpeza facial tratamento' => 'Limpeza facial tratamento',
                    '3--' => '',
                    'Massagem relaxante 30M' => 'Massagem relaxante 30M',
                    'Massagem relaxante 60M' => 'Massagem relaxante 60M',
                    'Massagem membros inferiores' => 'Massagem membros inferiores',
                    'Massagem abdomen' => 'Massagem abdomen'
                ]
            ])
            ->add('servico2', ChoiceType::class, [
                'choices'=>[
                    'Escolha' => null,
                    'Manicure' => 'Manicure',
                    'Verniz gel' => 'Verniz gel',
                    'Manutenção de unhas de gel' => 'Manutenção de unhas de gel',
                    'Aplicação de unhas de gel sem entenção' => 'Aplicação de unhas de gel sem entenção',
                    'Aplicação de unhas de gel com entenção' => 'Aplicação de unhas de gel com entenção',
                    'Pedicure' => 'Pedicure',
                    'Pedicure verniz gel' => 'Pedicure verniz gel',
                    'Parafina' => 'Parafina',
                    '1--' => '',
                    'Depilação perna inteira' => 'Depilação perna inteira',
                    'Depilação meia perna' => 'Depilação meia perna',
                    'Depilação virilhas' => 'Depilação virilhas',
                    'Depilação axilas' => 'Depilação axilas',
                    'Depilação buco' => 'Depilação buco',
                    'Depilação sobrancelhas' => 'Depilação sobrancelhas',
                    'Depilação pack' => 'Depilação pack',
                    'Depilação masculina ao peito' => 'Depilação masculina ao peito',
                    '2--' => '',
                    'Limpeza facial hidratação' => 'Limpeza facial hidratação',
                    'Limpeza facial tratamento' => 'Limpeza facial tratamento',
                    '3--' => '',
                    'Massagem relaxante 30M' => 'Massagem relaxante 30M',
                    'Massagem relaxante 60M' => 'Massagem relaxante 60M',
                    'Massagem membros inferiores' => 'Massagem membros inferiores',
                    'Massagem abdomen' => 'Massagem abdomen'
                ]
            ])
            ->add('servico3', ChoiceType::class, [
                'choices'=>[
                    'Escolha' => null,
                    'Manicure' => 'Manicure',
                    'Verniz gel' => 'Verniz gel',
                    'Manutenção de unhas de gel' => 'Manutenção de unhas de gel',
                    'Aplicação de unhas de gel sem entenção' => 'Aplicação de unhas de gel sem entenção',
                    'Aplicação de unhas de gel com entenção' => 'Aplicação de unhas de gel com entenção',
                    'Pedicure' => 'Pedicure',
                    'Pedicure verniz gel' => 'Pedicure verniz gel',
                    'Parafina' => 'Parafina',
                    '1--' => '',
                    'Depilação perna inteira' => 'Depilação perna inteira',
                    'Depilação meia perna' => 'Depilação meia perna',
                    'Depilação virilhas' => 'Depilação virilhas',
                    'Depilação axilas' => 'Depilação axilas',
                    'Depilação buco' => 'Depilação buco',
                    'Depilação sobrancelhas' => 'Depilação sobrancelhas',
                    'Depilação pack' => 'Depilação pack',
                    'Depilação masculina ao peito' => 'Depilação masculina ao peito',
                    '2--' => '',
                    'Limpeza facial hidratação' => 'Limpeza facial hidratação',
                    'Limpeza facial tratamento' => 'Limpeza facial tratamento',
                    '3--' => '',
                    'Massagem relaxante 30M' => 'Massagem relaxante 30M',
                    'Massagem relaxante 60M' => 'Massagem relaxante 60M',
                    'Massagem membros inferiores' => 'Massagem membros inferiores',
                    'Massagem abdomen' => 'Massagem abdomen'
                ]
            ])
            ->add('servico4', ChoiceType::class, [
                'choices'=>[
                    'Escolha' => null,
                    'Manicure' => 'Manicure',
                    'Verniz gel' => 'Verniz gel',
                    'Manutenção de unhas de gel' => 'Manutenção de unhas de gel',
                    'Aplicação de unhas de gel sem entenção' => 'Aplicação de unhas de gel sem entenção',
                    'Aplicação de unhas de gel com entenção' => 'Aplicação de unhas de gel com entenção',
                    'Pedicure' => 'Pedicure',
                    'Pedicure verniz gel' => 'Pedicure verniz gel',
                    'Parafina' => 'Parafina',
                    '1--' => '',
                    'Depilação perna inteira' => 'Depilação perna inteira',
                    'Depilação meia perna' => 'Depilação meia perna',
                    'Depilação virilhas' => 'Depilação virilhas',
                    'Depilação axilas' => 'Depilação axilas',
                    'Depilação buco' => 'Depilação buco',
                    'Depilação sobrancelhas' => 'Depilação sobrancelhas',
                    'Depilação pack' => 'Depilação pack',
                    'Depilação masculina ao peito' => 'Depilação masculina ao peito',
                    '2--' => '',
                    'Limpeza facial hidratação' => 'Limpeza facial hidratação',
                    'Limpeza facial tratamento' => 'Limpeza facial tratamento',
                    '3--' => '',
                    'Massagem relaxante 30M' => 'Massagem relaxante 30M',
                    'Massagem relaxante 60M' => 'Massagem relaxante 60M',
                    'Massagem membros inferiores' => 'Massagem membros inferiores',
                    'Massagem abdomen' => 'Massagem abdomen'
                ]
            ])
            ->add('marcacaoDia', DateType::class)
            ->add('marcacaoHora', TimeType::class)
            ->add('valor', NumberType::class)
            ->add('estado', HiddenType::class, ['data'=>'Agendado'])
            ->add('registo', HiddenType::class, array("mapped" => false))
            ->add('registo_update', HiddenType::class, array("mapped" => false))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Marcacoes::class,
        ]);
    }
}

src/Controller/MarcacoesController.php
<?php

namespace App\Controller;

use App\Entity\Marcacoes;
use App\Form\MarcacoesType;
use App\Repository\MarcacoesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/marcacoes")
 */
class MarcacoesController extends AbstractController
{
    /**
     * @Route("/", name="marcacoes_index", methods={"GET"})
     */
    public function index(MarcacoesRepository $marcacoesRepository): Response
    {
        return $this->render('marcacoes/index.html.twig', [
            'marcacoes' => $marcacoesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="marcacoes_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $marcaco = new Marcacoes();
        $form = $this->createForm(MarcacoesType::class, $marcaco);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($marcaco);
            $entityManager->flush();

            return $this->redirectToRoute('marcacoes_index');
        }

        return $this->render('marcacoes/new.html.twig', [
            'marcaco' => $marcaco,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="marcacoes_show", methods={"GET"})
     */
    public function show(Marcacoes $marcaco): Response
    {
        return $this->render('marcacoes/show.html.twig', [
            'marcaco' => $marcaco,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="marcacoes_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Marcacoes $marcaco): Response
    {
        $form = $this->createForm(MarcacoesType::class, $marcaco);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('marcacoes_index');
        }

        return $this->render('marcacoes/edit.html.twig', [
            'marcaco' => $marcaco,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="marcacoes_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Marcacoes $marcaco): Response
    {
        if ($this->isCsrfTokenValid('delete'.$marcaco->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($marcaco);
            $entityManager->flush();
        }

        return $this->redirectToRoute('marcacoes_index');
    }
}

templates/marcacoes/_delete_form.html.twig
<form method="post" action="{{ path('marcacoes_delete', {'id': marcaco.id}) }}" onsubmit="return confirm('Tem a certeza que pretender eliminar esta marcação?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ marcaco.id) }}">
    <button class="btn btn-outline-danger"><i class="fas fa-trash-alt"></i></button>
</form>

templates/marcacoes/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-info" title="GUARDAR">{{ button_label|default('GUARDAR') }}</button>
{{ form_end(form) }}

templates/marcacoes/edit.html.twig
{% extends 'base.html.twig' %}{% block title %}Edit Marcacoes{% endblock %}{% block body %}
<div class="container">
    {% block navbar %} {% include ('navbar.html.twig') %} {% endblock navbar %}
    <div class="py-3">
        <div class="row">
            <div class="col-md-10">
                <h6 class="ml-5 text-primary">Editar dados marcação</h6>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="ml-5 col-md-10 border border-warning">
            <div class="pt-2 text-left">
                {{ include('marcacoes/_form.html.twig', {'button_label': 'GUARDAR'}) }}
            </div>
            <div class="mb-3"></div>
        </div>
    </div>
    <div class="py-3">
        <div class="row">
            <div class="ml-5 col-md-10 text-center">
                <a href="{{ path('marcacoes_index') }}"> <button class="btn btn-outline-dark">Lista marcações</button></a>
            </div>
        </div>
    </div>
    {% block footer %} {% include ('footer.html.twig') %} {% endblock footer %}
</div>
{% endblock %}

templates/marcacoes/index.html.twig
{% extends 'base.html.twig' %}{% block title %}Marcacoes index{% endblock %}{% block body %}
<div class="container">
    {% block navbar %} {% include ('navbar.html.twig') %} {% endblock navbar %}
    <div class="row">
        <div class="col-md-12">
            <h6 class="ml-3 text-info">Marcações</h6>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive-sm">
                <table class="table table-hover table-sm">
                    <thead class="bg-dark text-info">
                        <tr>
                            <!--<th>Id</th>
                            <th>Nome</th>-->
                            <th>Servico</th>
                            <!--<th>Tiposervico2</th>
                            <th>Tiposervico3</th>
                            <th>Tiposervico4</th>-->
                            <th>Dia</th>
                            <th>Hora</th>
                            <!--<th>Notas</th>-->
                            <th>Estado</th>
                            <!--<th>Valor</th>
                            <th>Registo</th>
                            <th>Registo_update</th>-->
                            <th>Opções</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for marcaco in marcacoes %}
                        <tr>
                            <!--<td>{{ marcaco.id }}</td>-->
                            <td>{{ marcaco.servico1 }}</td>
                            <!--<td>{{ marcaco.servico2 }}</td>
                            <td>{{ marcaco.servico3 }}</td>
                            <td>{{ marcaco.servico4 }}</td>-->
                            <td>{{ marcaco.marcacaoDia ? marcaco.marcacaoDia|date('Y-m-d') : '' }}</td>
                            <td>{{ marcaco.marcacaoHora ? marcaco.marcacaoHora|date('H:i:s') : '' }}</td>
                            {#<td>{{ marcaco.notas }}</td>#}
                            {#<td>{{ marcaco.valor }}</td>#}
                            <td>{{ marcaco.estado }}</td>
                            {#<td>{{ marcaco.registo ? marcaco.registo|date('Y-m-d H:i:s') : '' }}</td>#}
                            {#<td>{{ marcaco.registoUpdate ? marcaco.registoUpdate|date('Y-m-d H:i:s') : '' }}</td>#}
                            <td>
                                <a href="{{ path('marcacoes_show', {'id': marcaco.id}) }}"><i class="fas fa-eye fa-1x text-info" title="Detalhes da marcação"></i></a>
                                <a href="{{ path('marcacoes_edit', {'id': marcaco.id}) }}"><i class="fas fa-edit fa-1x text-warning" title="Editar marcação"></i></a>
                                {#{{ include('marcacoes/_delete_form.html.twig') }}#}
                                <a href="{{ path('marcacoes_delete', {'id': marcaco.id}) }}"><i class="fas fa-trash-alt fa-1x text-danger" title="Eliminar marcação"></i></a>

                        </tr>
                        {% else %}
                        <tr>
                            <td colspan="14">Não existem Marcações</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 text-center">
            <p>
                <hr>
            </p>
            <a href="{{ path('marcacoes_new') }}"><button class="btn btn-outline-info" title="Criar nova marcação">CRIAR MARCAÇÃO</button></a>
        </div>
    </div>
    {% block footer %} {% include ('footer.html.twig') %} {% endblock footer %}
</div>

{% endblock %}

templates/marcacoes/new.html.twig
{% extends 'base.html.twig' %}{% block title %}New Marcacoes{% endblock %} {% block jquery%}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
{% endblock %} {% block body %}
<div class="container">
    {% block navbar %} {% include ('navbar.html.twig') %} {% endblock navbar %}
    <div class="py-3">
        <div class="row">
            <div class="ml-5 col-md-10">
                <h5 class="text-info">Nova Marcação</h5>
            </div>
        </div>
        <div class="row">
            <div class="ml-5 col-md-10 border border-warning">
                <br>{{ include('marcacoes/_form.html.twig') }}
                <br>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="ml-5 col-md-10 text-center">
            <a href="{{ path('marcacoes_index') }}"><button class="btn btn-outline-info" title="Lista de marcações">Lista marcações</button></a>
        </div>
    </div>
    {% block footer %} {% include ('footer.html.twig') %} {% endblock footer %}
</div>

{% block javascripts %} {{ parent() }} {{ encore_entry_script_tags('populate') }} {% endblock %} {% endblock %}

templates/marcacoes/show.html.twig
{% extends 'base.html.twig' %}{% block title %}Marcacoes{% endblock %}{% block body %}
<div class="container">
    {% block navbar %} {% include ('navbar.html.twig') %} {% endblock navbar %}
    <div class="py-3">
        <div class="row">
            <div class="col-md-10">
                <h5 class="ml-5 text-info">Marcação</h5>
            </div>
        </div>
    </div>
    <div class="py-1 ml-5 col-md-10 border border-warning">
        <div class="row">
            <div class="col-md-10">
                <br>
                <div class="table-responsive-md">
                    <table class="table">
                        <tbody>
                            <tr>
                                <th>Id</th>
                                <td>{{ marcaco.id }}</td>
                            </tr>
                            <tr>
                                <th>Cliente</th>
                                <td>{{ marcaco.idCliente }}</td>
                            </tr>
                            <tr>
                                <th>Serviço->1</th>
                                <td>{{ marcaco.servico1 }}</td>
                            </tr>
                            <tr>
                                <th>Serviço->2</th>
                                <td>{{ marcaco.servico2 }}</td>
                            </tr>
                            <tr>
                                <th>Serviço->3</th>
                                <td>{{ marcaco.servico3 }}</td>
                            </tr>
                            <tr>
                                <th>Servico->4</th>
                                <td>{{ marcaco.servico4 }}</td>
                            </tr>
                            <tr>
                                <th>Dia</th>
                                <td>{{ marcaco.marcacaoDia ? marcaco.marcacaoDia|date('d-m-Y') : '' }}</td>
                            </tr>
                            <tr>
                                <th>Hora</th>
                                <td>{{ marcaco.marcacaoHora ? marcaco.marcacaoHora|date('H:i:s') : '' }}</td>
                            </tr>
                            <!--<tr>
                                <th>Notas</th>
                                {#<td>{{ marcaco.notas }}</td>#}
                            </tr>-->
                            <tr>
                                <th>Valor</th>
                                <td>{{ marcaco.valor }}€</td>
                            </tr>
                            <tr>
                                <th>Status</th>
                                <td>{{ marcaco.estado }}</td>
                            </tr>
                            <tr>
                                <th>Registo</th>
                                <td>{{ marcaco.registo ? marcaco.registo|date('d-m-Y H:i:s') : '' }}</td>
                            </tr>
                            <tr>
                                <th>Registo_update</th>
                                <td>{{ marcaco.registoUpdate ? marcaco.registoUpdate|date('d-m-Y H:i:s') : '' }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="d-flex">
                <div class="ml-2">
                    <a href="{{ path('marcacoes_edit', {'id': marcaco.id}) }}"><button class="btn btn-outline-info"><i class="fas fa-pencil-alt fa-1x"></i></button></a>
                </div>
                <div class="m-2"></div>
                <div class="mr-2">
                    {{ include('marcacoes/_delete_form.html.twig', {'button_label': 'delete'}) }}
                </div>
            </div>
            <div class="m-3"> </div>
        </div>
    </div>
    <div class="py-3">
        <div class="row">
            <div class="ml-5 col-md-10 text-center">
                <a href="{{ path('marcacoes_index') }}"> <button class="btn btn-outline-info" title="Lista de marcações">Lista marcações</button></a>
            </div>
        </div>
    </div>
    {% block footer %} {% include ('footer.html.twig') %} {% endblock footer %}
</div>

{% endblock %}